lista = [1,2,3]
lista.append(4)
print(lista)
lista2 = [5,6]
lista.extend(lista2)
print(lista)
lista.insert(1,100)
print(lista)
print(lista.pop())
print(lista)
print(lista.pop(1))
print(lista)
lista.remove(3)
print(lista)
lista.reverse()
print(lista)
lista.sort()
print(lista)
lista.sort(reverse=True)
print(lista)
lista=["hola","que","tal","Hola","Que","Tal"]
lista.sort()
print(lista)
lista = [1, 2, 4, 5]
print(lista.count(5))
lista.append(5)
print(lista)
print(lista.count(5))
print(lista.index(5))
print(lista.index(5,3))
print(lista.index(5,4))
lista.append(1)
print(lista.index(1))
print(lista.index(1,1))
