string = "informatica"
print("a" in string)
print("b" in string)
print("info" in string)
print("a" not in string)
print(string[0])
print(string[2:5])
print(string[2:7])
print(string[2:7:2])
print(string[5:])
print(string[:5])
print(string[::-1])
num = str(6.7)
print(type(num))