name = input("Dime tu nombre:")
print(type(name))
num=int(input("Dame un número:"))
print(type(num))
num_float=float(input("Dame un número:"))
print(type(num_float))
print("Hola son las",6,"de la tarde")
print("Hola son las",str(6),"de la tarde")
print("El producto %s cantidad=%d precio=%f"%("cesta", 23, 13.456))
print("El producto %s cantidad=%d precio=%.2f"%("cesta", 23, 13.456))
